### ISSUE TITLE
Edits to package.json triggered watched build, but changes aren't reflected in libraries

### ISSUE THREAD

**Issue by jkinkead** [allenai/syrup#32]
When you update `package.json` to add a dependency, it triggered a build when `npm watch` is running, but the new build doesn't actually pull in the new dependency.

It should either not trigger an new build, or it should trigger an `npm install` (or whatever is required to regenerate dependencies).

**Comment by codeviking** [comment]
Weird.  Really weird.

The `package.json` file shouldn't be watched, as `watchify` only watches the js entry point, while the `gulp.watch` statements are only pointed at specific globs, none of which match the `.json` file.

I'll take a look and see if I can repro this.

**Comment by jkinkead** [comment]
[my deps](https://github.com/allenai/aristo/blob/master/tables/webapp/package.json), FWIW. I might be using out-of-date versions.
