### ISSUE TITLE
Add explicit REACT support 

### ISSUE THREAD

**Issue by codeviking** [allenai/syrup#6]
Hitup @afader (the React master :rocket:)

**Comment by afader** [comment]
:baby: you rang? :baby_bottle:

**Comment by codeviking** [comment]
It'll likely be cut n' paste, but I'm going to add explicit React support to syrup.  I'll have you upgrade to the latest version when that's ready

It's also got a lot simpler API.  So that should be nice n' such.

**Comment by afader** [comment]
Ok, cool! Lemme know. I'll probably need a lot of :baby:-sitting to do this.

**Comment by codeviking** [comment]
Will submit PR as mentioned.  Ready to go as of 0.0.50.
